@host = http://localhost
@port = 3000

@url = {{host}}:{{port}}

### get kategories
GET {{url}}/categories
Content-Type: application/json

### get category by id
GET http://localhost:3000/categories/1
Content-Type: application/json


### delete category by id
DELETE http://localhost:3000/categories/4
Content-Type: application/json

### post new category
POST http://localhost:3000/categories/
Content-Type: application/json

{
    "kategoriaNev": "Proba"
}

### PATCH category
PATCH http://localhost:3000/categories/3
Content-Type: application/json

{
    "kategoriaNev": "Desszertek"
}


### get forgalom
GET http://localhost:3000/traffic
Content-Type: application/json

### get traffic by id
GET http://localhost:3000/traffic/250
Content-Type: application/json


### POST traffic
POST http://localhost:3000/traffic
Content-Type: application/json

{
    "termek": "abc",
    "vevo": "Pista",
    "kategoriaId": 3,
    "egyseg": "db",
    "nettoar": 500,
    "mennyiseg": 6,
    "kiadva": 1
}

### PATCH traffic by id
PATCH http://localhost:3000/traffic/259
Content-Type: application/json

{
    "termek": "Lángos",
    "vevo": "Pista",
    "kategoriaId": 3,
    "egyseg": "db",
    "nettoar": 5000,
    "mennyiseg": 1,
    "kiadva": 1
}

### DELETE traffic by id
DELETE http://localhost:3000/traffic/260
Content-Type: application/json


### GET statistics
GET http://localhost:3000/statistics
Content-Type: application/json

### GET products
GET http://localhost:3000/products
Content-Type: application/json

### POST product
POST http://localhost:3000/products
Content-Type: application/json

{
    "termekNev": "teszt termék",
    "nettoAr": 300,
    "egyseg": "db",
    "kategoriaId": 2
}


### get one product by id
GET {{url}}/products/2
Content-Type: application/json

### get all vevo
GET {{url}}/customers
Content-Type: application/json


### get vevo by id
GET {{url}}/customers/2
Content-Type: application/json


### patch vevo by id
PATCH {{url}}/customers/6
Content-Type: application/json

{
    "nev": "Pista"
}


### delete vevo by id
DELETE {{url}}/customers/3
Content-Type: application/json


### POST vevo
POST {{url}}/customers
Content-Type: application/json

{
    "nev": "Sanyi"
}